### ISSUE TITLE
ImportError: cannot import name StanfordNERTagger

### ISSUE THREAD

**Issue by knilssen** [knilssen/Founding_Fathers#12]
```
Traceback (most recent call last):
  File "wa_run_test.py", line 19, in <module>
    import article_NERT_parser
  File "~/Founding_Fathers_K/Algorithm Code/article_NERT_parser.py", line 44, in <module>
    from nltk.tag.stanford import StanfordNERTagger
ImportError: cannot import name StanfordNERTagger
```

**Comment by knilssen** [comment]
Outdated nlp, after updating via pip, problem solved
